version: '3.8'

services:
  bot:
    build: .
    container_name: eve-market-bot
    restart: unless-stopped
    command: ["python", "bot.py"]
    volumes:
      - ./config.py:/app/config.py:ro
      - processed_data:/app/data
    depends_on:
      - webapp

  webapp:
    build: .
    container_name: eve-market-webapp
    restart: unless-stopped
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "webapp:app"]
    volumes:
      - ./config.py:/app/config.py:ro
      - processed_data:/app/data
    ports:
      - "5000:5000"

volumes:
  processed_data:
    driver: local