version: '3.8'

services:
  sales-order-bot:
    build: .
    container_name: sales-order-bot
    restart: unless-stopped
    # Before running 'docker-compose up', you must create a 'config.py' file
    # from the 'config.py.example' template and fill in your details.
    volumes:
      # Mount the config file to provide credentials to the bot
      - ./config.py:/app/config.py
      # Use a named volume to persist the processed transactions data inside the 'data' directory
      - processed_data:/app/data

# Defines the named volume for persisting data
volumes:
  processed_data:
    driver: local