version: '3.8'

services:
  sales-order-bot:
    build: .
    container_name: sales-order-bot
    restart: unless-stopped
    # Before running 'docker-compose up', you must create a 'config.py' file
    # from the 'config.py.example' template and fill in your details.
    volumes:
      # Mount the config file to provide credentials to the bot
      - ./config.py:/app/config.py:ro
      # Mount the database file directly to make it persistent and accessible on the host.
      # The bot will create this file on its first run.
      - ./bot_data.db:/app/bot_data.db