version: '3.8'

services:
  bot:
    build: .
    container_name: eve-market-bot
    restart: unless-stopped
    command: ["python", "bot.py"]
    volumes:
      - ./config.py:/app/config.py:ro
      - processed_data:/app/data
    depends_on:
      - webapp

  webapp:
    build: .
    container_name: eve-market-webapp
    restart: unless-stopped
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "webapp:app"]
    volumes:
      - ./config.py:/app/config.py:ro
      - processed_data:/app/data
    # Port is no longer exposed to the host; cloudflared handles access.

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: eve-market-cloudflared
    restart: unless-stopped
    depends_on:
      - webapp
    command: >
      sh -c '
        TOKEN=$$(awk -F ''"'' ''/CLOUDFLARE_TOKEN/ {print $$2}'' /etc/config.py);
        if [ -z "$$TOKEN" ] || [ "$$TOKEN" = "your_cloudflare_token_here" ]; then
          echo "CLOUDFLARE_TOKEN not found or is default. Tunnel not starting.";
          sleep infinity;
        else
          echo "Starting Cloudflare tunnel with token...";
          cloudflared tunnel --no-autoupdate run --token $$TOKEN;
        fi
      '
    volumes:
      - ./config.py:/etc/config.py:ro

volumes:
  processed_data:
    driver: local