version: '3.8'

services:
  sales-order-bot:
    build: .
    container_name: sales-order-bot
    restart: unless-stopped
    # Before running 'docker-compose up', you must create a 'config.py' file
    # from the 'config.py.example' template and fill in your details.
    volumes:
      # Mount the config file to provide credentials to the bot
      - ./config.py:/app/config.py:ro
      # Mount the entire 'data' directory to make the database persistent.
      # Docker will create the './data' directory on the host if it doesn't exist.
      - ./data:/app/data